### ISSUE TITLE
1.3.0 release checklist

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#1889]
This issue is a list of things we should do before publishing 1.3.x. A few PRs are in flights with some breaking changes and it's better if we make all of them at once and properly document them.

- [x] Removed singularization of non-list fields => https://github.com/apollographql/apollo-android/pull/1888
- [x] Allow nested class with the same name as their parent class without suffix => https://github.com/apollographql/apollo-android/pull/1893
- [x] Promote the incubating plugin => https://github.com/apollographql/apollo-android/pull/1673
- [x] Promote Gradle Plugin documentation + New plugin migration docs => https://github.com/apollographql/apollo-android/pull/1914
- [x] Duplicate classes for tests issue https://github.com/apollographql/apollo-android/issues/1906
- [x] Replaced transformed queries with operation output => https://github.com/apollographql/apollo-android/pull/1859
- [x] @includes fixes - https://github.com/apollographql/apollo-android/pull/1891
- [ ] More ? Feel free to comment or edit this issue

**Comment by tasomaniac** [comment]
Are we ready for 1.3 release? What else is blocking?

**Comment by martinbonnin** [comment]
I wanted to mention the idling resource artifact renaming too. I'll do that when I get back to my computer. Hopefully tonight

**Comment by tasomaniac** [comment]
Added here #1923.
