### ISSUE TITLE
2.0.0 release checklist

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#2057]
Placeholder for things to do before releasing version w
2.0.0

- [X] Migrate apollo-api to kotlin
- [x] Write a migration doc
- [X] CI setup to with MacOS Support (GitHub Actions?)
- [X] Gradle Plugin adjustments for Kotlin Multiplatform
- [x] Docs for Multiplatform support
- [x] Sample iOS app
- [x] streamline artifact publishing

Breaking changes:
* Boolean are now unboxed
* Final classes and methods
* Kotlin-stdlib transitive dependency
* Java version ? 
* Android API Level
* Gradle 6.x recommended. In 5.x, Gradle Metadata needs to be enabled by putting this into settings.gradle
`enableFeaturePreview("GRADLE_METADATA")`
* More ?

**Comment by tasomaniac** [comment]
Just like OkHttp, does this mean that our supported Android minSdk should be 21?

**Comment by martinbonnin** [comment]
> Just like OkHttp, does this mean that our supported Android minSdk should be 21?

I guess so... I'm not sure how to communicate that to consumers though given that `apollo-runtime` is a plain jar and not an aar.

**Comment by tasomaniac** [comment]
Hmm, this looks like a requirement related to TLS APIs being available only after Android API 21. I thought it was also related to Kotlin.

So we have the option to stay on an older version of OkHttp, then. I don't see any reason to do that though.

Apart from just documenting it in release notes, I don't think we can communicate it to users.
