### ISSUE TITLE
Create SqlLite Normalized Store

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#286]
I'll take this one, it will be an implementation of a normalized store in sqllite. I reached out to some android folks to answer questions about multi thread read writes

Tasks:

- [x] Create `SqliteHelper` with Table records and 3 fields (id, key, record) #298
- [x] Create `SqlStore` for reading writing records to DB, write should be compiled statement  #298
- [x] Create `RecordParser` to marshal/unmarshal record   #298
- [x] Create JsonAdapters for  `CacheReference` #265 
- [x] Make `SqlStore` implements `CacheStore` and connect to `RecordParser`  #298
- [ ] Create `ApolloSql` Module
- [x] Make Travis work with android connected tests (need to configure emulator) #301

**Comment by digitalbuddha** [comment]
@sav007 
Questions coming as I go through it:
How do I go from a `Record` `fields` to something that is serialized.  Ideally I should be able to get the raw json.

**Comment by digitalbuddha** [comment]
We will create Moshi Adapters for `Record` & `CacheReference` allowing us to use moshi to marshal/unmarshal a record field without any reflection.

**Comment by digitalbuddha** [comment]
how we should test https://github.com/chiuki/friendspell/blob/master/app/src/androidTest/java/com/sqisland/friendspell/storage/DatabaseApiTest.java

**Comment by digitalbuddha** [comment]
Going to close this as moving to another module is only task and will be split out
