### ISSUE TITLE
Misc Gradle Plugin Improvements

### ISSUE THREAD

**Issue by marwanad** [apollographql/apollo-android#95]
- [x] Support java projects in addition to android (PR: #106)
- [x] Have different `build.gradle` fixtures to test the extension options or TestRules instead (PR: #120)
- [x] Project-level extension with a `generatepojo` option (issue: #85, PR: #96)
- [x] Rewrite the plugin tasks and extensions in Java (PR: #119)
- [x] `gradleTestKit()` and setting classpath for plugin integration tests (PR: #120)
- [x] Dynamically add `apollo-api` dependency (PR: #125)
- [x] Refactor GraphQLExtension to make use of `DefaultSourceDirectorySet` 
- [x] Support multiple schema files under a sourceSet directory
- [x] Add the Tasks for test sourcesets as well (PR: )
- [x] Schema download task (issue: #91, PR: )
